title: LumbarSR: A Paired Clinical CT and Photon-Counting Micro-CT Dataset for Human Lumbar Vertebrae
description: A paired clinical CT and photon-counting micro-CT dataset for human lumbar vertebrae
theme: jekyll-theme-cayman
